export interface SofaPhoto {
  id: string;
  title: string;
  category: string;
  style: string;
  material: string;
  color: string;
  colorHex: string;
  url: string;
  downloadUrl: string;
  width: number;
  height: number;
  tags: string[];
  photographer: string;
  pexelsId?: number;
  hasFootstool?: boolean;
}

export const HD_SOFA_COLLECTION: SofaPhoto[] = [
  {
    id: 'pexels-14645214',
    title: 'Mayfair 4-Seater L-Shape Chaise Sectional with Deep Lounge Chaise',
    category: '4-seater',
    style: 'Organic Modern',
    material: 'Italian Alpine Bouclé',
    color: 'Earthen Sandstone',
    colorHex: '#7E5245',
    url: 'https://images.pexels.com/photos/14645214/pexels-photo-14645214.jpeg?auto=compress&cs=tinysrgb&w=1600&q=85',
    downloadUrl: 'https://images.pexels.com/photos/14645214/pexels-photo-14645214.jpeg',
    width: 4000,
    height: 3000,
    tags: ['4-seater', 'l-shape', 'chaise', 'sectional', 'bouclé', 'luxury', 'hd', 'furniture', 'veloura'],
    photographer: 'TONY BLACK',
    pexelsId: 14645214,
    hasFootstool: false,
  },
  {
    id: 'pexels-7045702',
    title: 'Chelsea 4-Seater Tuscan Leather Corner Sofa with Matching Ottoman Footstool',
    category: 'sectional',
    style: 'Architectural Modernist',
    material: 'Tuscan Saddle Leather',
    color: 'Cognac Amber',
    colorHex: '#B5A291',
    url: 'https://images.pexels.com/photos/7045702/pexels-photo-7045702.jpeg?auto=compress&cs=tinysrgb&w=1600&q=85',
    downloadUrl: 'https://images.pexels.com/photos/7045702/pexels-photo-7045702.jpeg',
    width: 7360,
    height: 4912,
    tags: ['sectional', '4-seater', 'leather', 'corner', 'footstool', 'ottoman', 'luxury', 'hd', 'furniture'],
    photographer: 'Max Vakhtbovych',
    pexelsId: 7045702,
    hasFootstool: true,
  },
  {
    id: 'pexels-7045712',
    title: 'Seraphina 4-Seater Sculpted Curved L-Sectional with Round Velvet Footstool',
    category: 'curved',
    style: 'Italian Mid-Century',
    material: 'Stain-Shield Alpaca Velvet',
    color: 'Charcoal Fog',
    colorHex: '#807166',
    url: 'https://images.pexels.com/photos/7045712/pexels-photo-7045712.jpeg?auto=compress&cs=tinysrgb&w=1600&q=85',
    downloadUrl: 'https://images.pexels.com/photos/7045712/pexels-photo-7045712.jpeg',
    width: 7360,
    height: 4912,
    tags: ['curved', '4-seater', 'l-shape', 'sculptural', 'velvet', 'footstool', 'ottoman', 'luxury', 'hd'],
    photographer: 'Max Vakhtbovych',
    pexelsId: 7045712,
    hasFootstool: true,
  },
  {
    id: 'pexels-31737854',
    title: 'Køben 4-Seater Modular L-Shape Pit Lounge with Deep Plush Ottoman Footstool',
    category: 'modular',
    style: 'Scandinavian Natural',
    material: 'Belgian Washed Linen',
    color: 'Earthen Sandstone',
    colorHex: '#A69B89',
    url: 'https://images.pexels.com/photos/31737854/pexels-photo-31737854.jpeg?auto=compress&cs=tinysrgb&w=1600&q=85',
    downloadUrl: 'https://images.pexels.com/photos/31737854/pexels-photo-31737854.jpeg',
    width: 5929,
    height: 3953,
    tags: ['modular', 'pit-lounge', '4-seater', 'l-shape', 'linen', 'footstool', 'ottoman', 'luxury', 'hd'],
    photographer: 'Sharath G.',
    pexelsId: 31737854,
    hasFootstool: true,
  },
  {
    id: 'pexels-37110858',
    title: 'Aurelia 4-Seater Cloud L-Sectional with Low-Profile Center Ottoman',
    category: '4-seater',
    style: 'Contemporary Luxury',
    material: 'Textured Alpine Melange',
    color: 'Cognac Amber',
    colorHex: '#837665',
    url: 'https://images.pexels.com/photos/37110858/pexels-photo-37110858.jpeg?auto=compress&cs=tinysrgb&w=1600&q=85',
    downloadUrl: 'https://images.pexels.com/photos/37110858/pexels-photo-37110858.jpeg',
    width: 4032,
    height: 3024,
    tags: ['4-seater', 'l-shape', 'sectional', 'footstool', 'ottoman', 'luxury', 'hd'],
    photographer: 'Century21 lebanon',
    pexelsId: 37110858,
    hasFootstool: true,
  },
  {
    id: 'pexels-12498613',
    title: 'Verona 4-Seater Motorized Reclining Leather L-Sectional with Extended Footrest',
    category: 'reclining',
    style: 'Minimalist Penthouse',
    material: 'Top-Grain Aniline Leather',
    color: 'Charcoal Fog',
    colorHex: '#AFADAE',
    url: 'https://images.pexels.com/photos/12498613/pexels-photo-12498613.jpeg?auto=compress&cs=tinysrgb&w=1600&q=85',
    downloadUrl: 'https://images.pexels.com/photos/12498613/pexels-photo-12498613.jpeg',
    width: 4000,
    height: 2670,
    tags: ['reclining', '4-seater', 'l-shape', 'leather', 'footrest', 'footstool', 'luxury', 'hd', 'motorized'],
    photographer: 'Viaceslav Kat',
    pexelsId: 12498613,
    hasFootstool: true,
  },
  {
    id: 'pexels-37110860',
    title: 'Montauk 4-Seater Convertible L-Shape Sleeper Lounge with Tufted Movable Footstool',
    category: 'sofa-bed',
    style: 'Japandi Serenity',
    material: 'Royal Cotton Velvet',
    color: 'Earthen Sandstone',
    colorHex: '#6D5E4B',
    url: 'https://images.pexels.com/photos/37110860/pexels-photo-37110860.jpeg?auto=compress&cs=tinysrgb&w=1600&q=85',
    downloadUrl: 'https://images.pexels.com/photos/37110860/pexels-photo-37110860.jpeg',
    width: 4032,
    height: 3024,
    tags: ['sofa-bed', '4-seater', 'l-shape', 'sleeper', 'velvet', 'footstool', 'ottoman', 'luxury', 'hd'],
    photographer: 'Century21 lebanon',
    pexelsId: 37110860,
    hasFootstool: true,
  },
  {
    id: 'pexels-7546213',
    title: 'Belgravia 4-Seater Penthouse L-Sectional in Charcoal Fog Alpaca Velvet',
    category: '4-seater',
    style: 'Contemporary Penthouse',
    material: 'Stain-Shield Alpaca Velvet',
    color: 'Charcoal Fog',
    colorHex: '#353538',
    url: 'https://images.pexels.com/photos/7546213/pexels-photo-7546213.jpeg?auto=compress&cs=tinysrgb&w=1600&q=85',
    downloadUrl: 'https://images.pexels.com/photos/7546213/pexels-photo-7546213.jpeg',
    width: 4800,
    height: 3200,
    tags: ['4-seater', 'l-shape', 'sectional', 'velvet', 'dark-luxury', 'penthouse', 'hd'],
    photographer: 'Rachel Claire',
    pexelsId: 7546213,
    hasFootstool: false,
  },
  {
    id: 'pexels-3935315',
    title: 'Elysian 4-Seater High-Lounge Modular L-Sofa with Matching Velvet Footstool',
    category: 'modular',
    style: 'Modern Minimalist',
    material: 'Italian Bouclé',
    color: 'Cream Bouclé',
    colorHex: '#ECE7DE',
    url: 'https://images.pexels.com/photos/3935315/pexels-photo-3935315.jpeg?auto=compress&cs=tinysrgb&w=1600&q=85',
    downloadUrl: 'https://images.pexels.com/photos/3935315/pexels-photo-3935315.jpeg',
    width: 4000,
    height: 2667,
    tags: ['modular', '4-seater', 'l-shape', 'bouclé', 'footstool', 'ottoman', 'minimalist', 'luxury'],
    photographer: 'Tatiana Syrikova',
    pexelsId: 3935315,
    hasFootstool: true,
  },
  {
    id: 'pexels-8082330',
    title: 'Montauk 4-Piece Modular Corner Lounge with Matching Footstool',
    category: 'modular',
    style: 'Contemporary Scandinavian',
    material: 'Belgian Washed Linen',
    color: 'Charcoal Fog',
    colorHex: '#6E6A64',
    url: 'https://images.pexels.com/photos/8082330/pexels-photo-8082330.jpeg?auto=compress&cs=tinysrgb&w=1600&q=85',
    downloadUrl: 'https://images.pexels.com/photos/8082330/pexels-photo-8082330.jpeg',
    width: 6000,
    height: 4000,
    tags: ['modular', '4-seater', 'corner', 'l-shape', 'footstool', 'ottoman', 'linen', 'scandinavian'],
    photographer: 'Max Vakhtbovych',
    pexelsId: 8082330,
    hasFootstool: true,
  },
  {
    id: 'pexels-39134566',
    title: 'Solis Curved 4-Seater Conversation Sofa with Sculptural Oval Footstool',
    category: 'curved',
    style: 'Bespoke Organic',
    material: 'Italian Bouclé',
    color: 'Cream Bouclé',
    colorHex: '#F2EDE4',
    url: 'https://images.pexels.com/photos/39134566/pexels-photo-39134566.jpeg?auto=compress&cs=tinysrgb&w=1600&q=85',
    downloadUrl: 'https://images.pexels.com/photos/39134566/pexels-photo-39134566.jpeg',
    width: 4800,
    height: 3200,
    tags: ['curved', '4-seater', 'bouclé', 'footstool', 'ottoman', 'conversation-sofa'],
    photographer: 'Design Workshop',
    pexelsId: 39134566,
    hasFootstool: true,
  },
  {
    id: 'pexels-7018400',
    title: 'Mayfair 4-Seater L-Shape Lounge in Deep Forest Italian Velvet with Footstool',
    category: '4-seater',
    style: 'Modern British Luxury',
    material: 'Stain-Shield Alpaca Velvet',
    color: 'Deep Forest Velvet',
    colorHex: '#25382B',
    url: 'https://images.pexels.com/photos/7018400/pexels-photo-7018400.jpeg?auto=compress&cs=tinysrgb&w=1600&q=85',
    downloadUrl: 'https://images.pexels.com/photos/7018400/pexels-photo-7018400.jpeg',
    width: 4500,
    height: 3000,
    tags: ['4-seater', 'l-shape', 'velvet', 'green', 'footstool', 'ottoman', 'luxury'],
    photographer: 'Max Vakhtbovych',
    pexelsId: 7018400,
    hasFootstool: true,
  },
  {
    id: 'pexels-39134615',
    title: 'Chelsea Low-Profile 4-Seater Corner Sofa in Washed Belgian Charcoal Linen',
    category: 'sectional',
    style: 'Contemporary Italian',
    material: 'Belgian Washed Linen',
    color: 'Charcoal Belgian Linen',
    colorHex: '#353538',
    url: 'https://images.pexels.com/photos/39134615/pexels-photo-39134615.jpeg?auto=compress&cs=tinysrgb&w=1600&q=85',
    downloadUrl: 'https://images.pexels.com/photos/39134615/pexels-photo-39134615.jpeg',
    width: 4800,
    height: 3200,
    tags: ['sectional', '4-seater', 'corner', 'l-shape', 'linen', 'charcoal', 'luxury'],
    photographer: 'Design Workshop',
    pexelsId: 39134615,
    hasFootstool: false,
  },
  {
    id: 'pexels-13793273',
    title: 'Windsor Tailored 4-Seater Sofa in Olive Melange with Tufted Footstool',
    category: '4-seater',
    style: 'Modern British',
    material: 'Textured Melange',
    color: 'Olive Melange',
    colorHex: '#424C36',
    url: 'https://images.pexels.com/photos/13793273/pexels-photo-13793273.jpeg?auto=compress&cs=tinysrgb&w=1600&q=85',
    downloadUrl: 'https://images.pexels.com/photos/13793273/pexels-photo-13793273.jpeg',
    width: 4000,
    height: 2667,
    tags: ['4-seater', 'melange', 'footstool', 'ottoman', 'british', 'luxury'],
    photographer: 'Jonathan Borba',
    pexelsId: 13793273,
    hasFootstool: true,
  },
  {
    id: 'pexels-7598130',
    title: 'Cloudsink 4-Seater Pit Sectional with Dual Magnetic Ottomans & Footstools',
    category: 'modular',
    style: 'Ultra-Deep Cloud Lounger',
    material: 'Italian Alpine Bouclé',
    color: 'Cream Bouclé',
    colorHex: '#F5EFEB',
    url: 'https://images.pexels.com/photos/7598130/pexels-photo-7598130.jpeg?auto=compress&cs=tinysrgb&w=1600&q=85',
    downloadUrl: 'https://images.pexels.com/photos/7598130/pexels-photo-7598130.jpeg',
    width: 5000,
    height: 3333,
    tags: ['modular', '4-seater', 'l-shape', 'pit-lounge', 'footstool', 'ottoman', 'cloud-sink'],
    photographer: 'Rachel Claire',
    pexelsId: 7598130,
    hasFootstool: true,
  },
  {
    id: 'pexels-6510974',
    title: 'Chelsea 4-Seater L-Shape Leather Chaise with Low-Slung Solid Beech Frame',
    category: 'sectional',
    style: 'Contemporary Italian',
    material: 'Tuscan Saddle Leather',
    color: 'Tuscan Cognac',
    colorHex: '#8B4E2B',
    url: 'https://images.pexels.com/photos/6510974/pexels-photo-6510974.jpeg?auto=compress&cs=tinysrgb&w=1600&q=85',
    downloadUrl: 'https://images.pexels.com/photos/6510974/pexels-photo-6510974.jpeg',
    width: 5000,
    height: 3333,
    tags: ['4-seater', 'l-shape', 'leather', 'chaise', 'italian-luxury'],
    photographer: 'Rachel Claire',
    pexelsId: 6510974,
    hasFootstool: false,
  }
];
